export const AG_GRID_LOCALE = {
    page: 'Pag.',
    more: 'Mas',
    to: 'Al',
    of: 'De',
    next: 'Siguiente',
    last: 'Ultimo',
    first: 'Primero',
    previous: 'Anterior',
    loadingOoo: 'Cargando Datos...',
    selectAll: 'Seleccionar Todo',
    searchOoo: 'Buscar...',
    blanks: 'daBlanc',
    filterOoo: 'daFilter...',
    equals: 'Igual a',
    notEqual: 'Diferente a',
    dateFormatOoo: 'yyyy-mm-dd',
    lessThan: 'Inferior a',
    greaterThan: 'Superior a',
    lessThanOrEqual: 'Menor o Igual a',
    greaterThanOrEqual: 'Superorio o Igual a',
    inRange: 'En Rango',
    inRangeStart: 'Desde',
    inRangeEnd: 'Hasta',
    contains: 'Contiene',
    notContains: 'No Contiene',
    startsWith: 'Inicia Con',
    endsWith: 'Termina En',
    andCondition: 'Y',
    orCondition: 'O',
    applyFilter: 'Aplicar',
    resetFilter: 'Resetear',
    clearFilter: 'Limpiar',
    // other
    noRowsToShow: 'No hay datos para mostrar'

};
